use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::catalog::ResolvedTarget;
use crate::pipeline::{WorkspacePaths, default_output_dir, ensure_clean_dir, write_string};
use crate::spec::{OpenApiSpec, OperationRecord};

pub const MANIFEST_FILENAME: &str = "printing-press-rs-manifest.json";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedManifest {
    pub name: String,
    pub display_name: String,
    pub source_target: String,
    pub spec_source: String,
    pub generated_crate: String,
    pub base_url: String,
    pub operation_count: usize,
    pub operations: Vec<OperationRecord>,
}

#[derive(Debug, Clone, Serialize)]
pub struct GenerationResult {
    pub output_dir: PathBuf,
    pub manifest_path: PathBuf,
    pub crate_dir: PathBuf,
    pub operation_count: usize,
}

pub async fn generate_project(
    workspace: &WorkspacePaths,
    resolved: &ResolvedTarget,
    spec: &OpenApiSpec,
    output_override: Option<PathBuf>,
    force: bool,
) -> Result<GenerationResult> {
    let output_dir =
        output_override.unwrap_or_else(|| default_output_dir(workspace, &resolved.slug));
    ensure_clean_dir(&output_dir, force).await?;

    let crate_name = format!("{}-pp-cli", resolved.slug);
    let crate_dir = output_dir.join(&crate_name);
    let src_dir = crate_dir.join("src");
    tokio::fs::create_dir_all(&src_dir)
        .await
        .with_context(|| format!("creating generated crate {}", crate_dir.display()))?;

    let operations = spec.operations();
    let manifest = GeneratedManifest {
        name: resolved.slug.clone(),
        display_name: resolved.display_name.clone(),
        source_target: resolved.input.clone(),
        spec_source: resolved.spec_source.clone().unwrap_or_default(),
        generated_crate: crate_name.clone(),
        base_url: spec.base_url(),
        operation_count: operations.len(),
        operations,
    };

    write_string(
        &crate_dir.join("Cargo.toml"),
        &render_generated_cargo(&crate_name),
    )
    .await?;
    write_string(&src_dir.join("main.rs"), &render_generated_main(&manifest)).await?;
    write_string(&output_dir.join("README.md"), &render_readme(&manifest)).await?;
    write_string(
        &output_dir.join(MANIFEST_FILENAME),
        &serde_json::to_string_pretty(&manifest).context("serializing generation manifest")?,
    )
    .await?;

    Ok(GenerationResult {
        manifest_path: output_dir.join(MANIFEST_FILENAME),
        crate_dir,
        output_dir,
        operation_count: manifest.operation_count,
    })
}

pub async fn load_manifest(dir: &Path) -> Result<GeneratedManifest> {
    let manifest_path = dir.join(MANIFEST_FILENAME);
    let text = tokio::fs::read_to_string(&manifest_path)
        .await
        .with_context(|| format!("reading manifest {}", manifest_path.display()))?;
    serde_json::from_str(&text).context("parsing manifest JSON")
}

fn render_generated_cargo(crate_name: &str) -> String {
    format!(
        "[package]\nname = \"{crate_name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\nclap = {{ version = \"4\", features = [\"derive\"] }}\nserde = {{ version = \"1\", features = [\"derive\"] }}\nserde_json = \"1\"\n"
    )
}

fn render_generated_main(manifest: &GeneratedManifest) -> String {
    let enum_variants = manifest
        .operations
        .iter()
        .map(|operation| format!("    {},", enum_variant(&operation.command_name)))
        .collect::<Vec<_>>()
        .join("\n");

    let match_arms = manifest
        .operations
        .iter()
        .map(|operation| {
            format!(
                "        Command::{} => print_operation(\"{}\", \"{}\", \"{}\"),",
                enum_variant(&operation.command_name),
                operation.method,
                operation.path,
                escape_string(&operation.summary)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "use clap::{{Parser, Subcommand}};\n\n#[derive(Debug, Parser)]\n#[command(name = \"{name}\")]\n#[command(about = \"Generated by printing-press-rs\", long_about = None)]\nstruct Cli {{\n    #[command(subcommand)]\n    command: Command,\n}}\n\n#[derive(Debug, Subcommand)]\nenum Command {{\n{enum_variants}\n}}\n\nfn main() {{\n    let cli = Cli::parse();\n    match cli.command {{\n{match_arms}\n    }}\n}}\n\nfn print_operation(method: &str, path: &str, summary: &str) {{\n    println!(\"{{}} {{}}\", method, path);\n    println!(\"summary: {{}}\", summary);\n}}\n",
        name = manifest.generated_crate,
        enum_variants = enum_variants,
        match_arms = match_arms,
    )
}

fn render_readme(manifest: &GeneratedManifest) -> String {
    format!(
        "# {}\n\nGenerated by `printing-press-rs`.\n\n- Source target: `{}`\n- Spec source: `{}`\n- Base URL: `{}`\n- Operations: {}\n",
        manifest.generated_crate,
        manifest.source_target,
        manifest.spec_source,
        manifest.base_url,
        manifest.operation_count
    )
}

fn enum_variant(command_name: &str) -> String {
    command_name
        .split('-')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => format!("{}{}", first.to_ascii_uppercase(), chars.as_str()),
                None => String::new(),
            }
        })
        .collect::<String>()
}

fn escape_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
