use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::catalog::ResolvedTarget;
use crate::pipeline::{WorkspacePaths, default_output_dir, ensure_clean_dir, write_string};
use crate::spec::{AuthEnvVar, AuthModel, OpenApiSpec, OperationField, OperationRecord, upper_snake};

pub const MANIFEST_FILENAME: &str = "printing-press-rs-manifest.json";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedManifest {
    pub name: String,
    pub display_name: String,
    pub source_target: String,
    pub spec_source: String,
    pub generated_crate: String,
    pub base_url: String,
    pub operation_count: usize,
    pub operations: Vec<OperationRecord>,
    pub auth: Option<AuthModel>,
}

#[derive(Debug, Clone, Serialize)]
pub struct GenerationResult {
    pub output_dir: PathBuf,
    pub manifest_path: PathBuf,
    pub crate_dir: PathBuf,
    pub operation_count: usize,
}

pub async fn generate_project(
    workspace: &WorkspacePaths,
    resolved: &ResolvedTarget,
    spec: &OpenApiSpec,
    output_override: Option<PathBuf>,
    force: bool,
) -> Result<GenerationResult> {
    let output_dir =
        output_override.unwrap_or_else(|| default_output_dir(workspace, &resolved.slug));
    ensure_clean_dir(&output_dir, force).await?;

    let crate_name = format!("{}-pp-cli", resolved.slug);
    let crate_dir = output_dir.join(&crate_name);
    let src_dir = crate_dir.join("src");
    tokio::fs::create_dir_all(&src_dir)
        .await
        .with_context(|| format!("creating generated crate {}", crate_dir.display()))?;

    let operations = spec.operations();
    let manifest = GeneratedManifest {
        name: resolved.slug.clone(),
        display_name: resolved.display_name.clone(),
        source_target: resolved.input.clone(),
        spec_source: resolved.spec_source.clone().unwrap_or_default(),
        generated_crate: crate_name.clone(),
        base_url: spec.base_url(),
        operation_count: operations.len(),
        operations,
        auth: spec.auth_model(),
    };

    write_string(
        &crate_dir.join("Cargo.toml"),
        &render_generated_cargo(&crate_name),
    )
    .await?;
    write_string(&src_dir.join("main.rs"), &render_generated_main(&manifest)).await?;
    write_string(&output_dir.join("README.md"), &render_readme(&manifest)).await?;
    write_string(
        &output_dir.join(MANIFEST_FILENAME),
        &serde_json::to_string_pretty(&manifest).context("serializing generation manifest")?,
    )
    .await?;

    Ok(GenerationResult {
        manifest_path: output_dir.join(MANIFEST_FILENAME),
        crate_dir,
        output_dir,
        operation_count: manifest.operation_count,
    })
}

pub async fn load_manifest(dir: &Path) -> Result<GeneratedManifest> {
    let manifest_path = dir.join(MANIFEST_FILENAME);
    let text = tokio::fs::read_to_string(&manifest_path)
        .await
        .with_context(|| format!("reading manifest {}", manifest_path.display()))?;
    serde_json::from_str(&text).context("parsing manifest JSON")
}

fn render_generated_cargo(crate_name: &str) -> String {
    format!(
        "[package]\nname = \"{crate_name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\nanyhow = \"1\"\nclap = {{ version = \"4\", features = [\"derive\"] }}\nserde = {{ version = \"1\", features = [\"derive\"] }}\nserde_json = \"1\"\n"
    )
}

fn render_generated_main(manifest: &GeneratedManifest) -> String {
    let mut out = String::new();
    out.push_str("use anyhow::{Context, Result, bail};\n");
    out.push_str("use clap::{Args, Parser, Subcommand};\n");
    out.push_str("use serde::{Deserialize, Serialize};\n");
    out.push_str("use serde_json::json;\n");
    out.push_str("use std::env;\n");
    out.push_str("use std::fs;\n");
    out.push_str("use std::path::PathBuf;\n\n");

    out.push_str("#[derive(Debug, Parser)]\n");
    writeln!(out, "#[command(name = \"{}\")]", manifest.generated_crate).unwrap();
    out.push_str("#[command(about = \"Generated by printing-press-rs\", long_about = None)]\n");
    out.push_str("struct Cli {\n");
    writeln!(
        out,
        "    #[arg(long, default_value = \"{}\")]",
        escape_string(&manifest.base_url)
    )
    .unwrap();
    out.push_str("    base_url: String,\n");
    out.push_str("    #[command(subcommand)]\n");
    out.push_str("    command: Command,\n");
    out.push_str("}\n\n");

    out.push_str("#[derive(Debug, Subcommand)]\n");
    out.push_str("enum Command {\n");
    if manifest.auth.is_some() {
        out.push_str("    Auth(AuthCommand),\n");
    }
    for operation in &manifest.operations {
        writeln!(
            out,
            "    {}({}),",
            enum_variant(&operation.command_name),
            args_struct_name(operation)
        )
        .unwrap();
    }
    out.push_str("}\n\n");

    if manifest.auth.is_some() {
        out.push_str(&render_auth_structs());
    }
    for operation in &manifest.operations {
        out.push_str(&render_operation_args_struct(operation));
    }

    out.push_str("fn main() -> Result<()> {\n");
    out.push_str("    let cli = Cli::parse();\n");
    out.push_str("    match cli.command {\n");
    if manifest.auth.is_some() {
        out.push_str("        Command::Auth(command) => run_auth(command),\n");
    }
    for operation in &manifest.operations {
        writeln!(
            out,
            "        Command::{}(args) => run_{}(&cli.base_url, args),",
            enum_variant(&operation.command_name),
            fn_suffix(operation)
        )
        .unwrap();
    }
    out.push_str("    }\n");
    out.push_str("}\n\n");

    if let Some(auth) = &manifest.auth {
        out.push_str(&render_auth_impl(manifest, auth));
    }
    for operation in &manifest.operations {
        out.push_str(&render_operation_runner(operation));
    }
    out
}

fn render_auth_structs() -> String {
    let mut out = String::new();
    out.push_str("#[derive(Debug, Args)]\n");
    out.push_str("struct AuthCommand {\n");
    out.push_str("    #[command(subcommand)]\n");
    out.push_str("    command: AuthSubcommand,\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug, Subcommand)]\n");
    out.push_str("enum AuthSubcommand {\n");
    out.push_str("    Status,\n");
    out.push_str("    SetToken { token: String },\n");
    out.push_str("    Logout,\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug, Serialize, Deserialize, Default)]\n");
    out.push_str("struct StoredAuth {\n");
    out.push_str("    token: String,\n");
    out.push_str("}\n\n");
    out
}

fn render_operation_args_struct(operation: &OperationRecord) -> String {
    let mut out = String::new();
    out.push_str("#[derive(Debug, Args)]\n");
    writeln!(out, "struct {} {{", args_struct_name(operation)).unwrap();
    for field in operation
        .path_fields
        .iter()
        .chain(operation.query_fields.iter())
        .chain(operation.body_fields.iter())
    {
        writeln!(out, "{}", render_field(field)).unwrap();
    }
    out.push_str("}\n\n");
    out
}

fn render_field(field: &OperationField) -> String {
    let required_attr = if field.required { ", required = true" } else { "" };
    format!(
        "    #[arg(long = \"{}\"{})]\n    {}: {},",
        field.flag_name,
        required_attr,
        field.rust_name,
        rust_type(field)
    )
}

fn rust_type(field: &OperationField) -> &'static str {
    match (field.field_type.as_str(), field.required) {
        ("boolean", true) => "bool",
        ("boolean", false) => "Option<bool>",
        ("integer", true) => "i64",
        ("integer", false) => "Option<i64>",
        ("number", true) => "f64",
        ("number", false) => "Option<f64>",
        (_, true) => "String",
        _ => "Option<String>",
    }
}

fn render_auth_impl(manifest: &GeneratedManifest, auth: &AuthModel) -> String {
    let mut out = String::new();
    let env_vars = auth_env_vars(manifest, auth);
    let usable_env_vars = usable_auth_env_vars(&env_vars, auth);

    writeln!(out, "const AUTH_HEADER_NAME: &str = \"{}\";", escape_string(&auth.header_name)).unwrap();
    writeln!(out, "const AUTH_KIND: &str = \"{}\";", escape_string(&auth.kind)).unwrap();
    writeln!(out, "const GENERATED_CLI_NAME: &str = \"{}\";", escape_string(&manifest.generated_crate)).unwrap();
    writeln!(
        out,
        "const AUTH_ENV_VARS: &[&str] = &[{}];",
        env_vars
            .iter()
            .map(|env_var| format!("\"{}\"", escape_string(&env_var.name)))
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    writeln!(
        out,
        "const USABLE_AUTH_ENV_VARS: &[&str] = &[{}];",
        usable_env_vars
            .iter()
            .map(|env_var| format!("\"{}\"", escape_string(&env_var.name)))
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    if let Some(token_url) = &auth.token_url {
        writeln!(out, "const AUTH_TOKEN_URL: Option<&str> = Some(\"{}\");", escape_string(token_url)).unwrap();
    } else {
        out.push_str("const AUTH_TOKEN_URL: Option<&str> = None;\n");
    }
    out.push_str("\n");

    out.push_str("fn run_auth(command: AuthCommand) -> Result<()> {\n");
    out.push_str("    match command.command {\n");
    out.push_str("        AuthSubcommand::Status => {\n");
    out.push_str("            let stored = load_stored_auth()?;\n");
    out.push_str("            let configured_env = AUTH_ENV_VARS.iter().find_map(|name| {\n");
    out.push_str("                env::var(name).ok().filter(|value| !value.trim().is_empty()).map(|_| (*name).to_string())\n");
    out.push_str("            });\n");
    out.push_str("            let configured = configured_env.is_some() || !stored.token.trim().is_empty();\n");
    out.push_str("            println!(\"{}\", serde_json::to_string_pretty(&json!({\n");
    out.push_str("                \"configured\": configured,\n");
    out.push_str("                \"header_name\": AUTH_HEADER_NAME,\n");
    out.push_str("                \"env_vars\": AUTH_ENV_VARS,\n");
    out.push_str("                \"configured_from\": configured_env.unwrap_or_else(|| if stored.token.trim().is_empty() { \"none\".to_string() } else { \"config\".to_string() }),\n");
    out.push_str("                \"config_path\": config_file_path()?,\n");
    out.push_str("                \"token_url\": AUTH_TOKEN_URL,\n");
    out.push_str("            }))?);\n");
    out.push_str("            Ok(())\n");
    out.push_str("        }\n");
    out.push_str("        AuthSubcommand::SetToken { token } => {\n");
    out.push_str("            let path = save_token(&token)?;\n");
    out.push_str("            println!(\"{}\", serde_json::to_string_pretty(&json!({\n");
    out.push_str("                \"saved\": true,\n");
    out.push_str("                \"config_path\": path,\n");
    out.push_str("            }))?);\n");
    out.push_str("            Ok(())\n");
    out.push_str("        }\n");
    out.push_str("        AuthSubcommand::Logout => {\n");
    out.push_str("            clear_token()?;\n");
    out.push_str("            println!(\"{}\", serde_json::to_string_pretty(&json!({\n");
    out.push_str("                \"cleared\": true,\n");
    out.push_str("                \"config_path\": config_file_path()?,\n");
    out.push_str("            }))?);\n");
    out.push_str("            Ok(())\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("fn config_file_path() -> Result<PathBuf> {\n");
    out.push_str("    let home = env::var(\"HOME\").context(\"HOME not set\")?;\n");
    out.push_str("    Ok(PathBuf::from(home).join(\".config\").join(GENERATED_CLI_NAME).join(\"auth.json\"))\n");
    out.push_str("}\n\n");

    out.push_str("fn load_stored_auth() -> Result<StoredAuth> {\n");
    out.push_str("    let path = config_file_path()?;\n");
    out.push_str("    if !path.exists() {\n");
    out.push_str("        return Ok(StoredAuth::default());\n");
    out.push_str("    }\n");
    out.push_str("    let text = fs::read_to_string(&path).with_context(|| format!(\"reading auth config {}\", path.display()))?;\n");
    out.push_str("    Ok(serde_json::from_str(&text).with_context(|| format!(\"parsing auth config {}\", path.display()))?)\n");
    out.push_str("}\n\n");

    out.push_str("fn save_token(token: &str) -> Result<PathBuf> {\n");
    out.push_str("    let path = config_file_path()?;\n");
    out.push_str("    if let Some(parent) = path.parent() {\n");
    out.push_str("        fs::create_dir_all(parent).with_context(|| format!(\"creating auth dir {}\", parent.display()))?;\n");
    out.push_str("    }\n");
    out.push_str("    fs::write(&path, serde_json::to_vec_pretty(&StoredAuth { token: token.to_string() })?)\n");
    out.push_str("        .with_context(|| format!(\"writing auth config {}\", path.display()))?;\n");
    out.push_str("    Ok(path)\n");
    out.push_str("}\n\n");

    out.push_str("fn clear_token() -> Result<()> {\n");
    out.push_str("    let path = config_file_path()?;\n");
    out.push_str("    if path.exists() {\n");
    out.push_str("        fs::remove_file(&path).with_context(|| format!(\"removing auth config {}\", path.display()))?;\n");
    out.push_str("    }\n");
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");

    out.push_str("fn resolve_auth_header() -> Result<String> {\n");
    out.push_str("    for env_var in USABLE_AUTH_ENV_VARS {\n");
    out.push_str("        if let Ok(value) = env::var(env_var) {\n");
    out.push_str("            if !value.trim().is_empty() {\n");
    out.push_str("                return Ok(format_auth_value(&value));\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    let stored = load_stored_auth()?;\n");
    out.push_str("    if !stored.token.trim().is_empty() {\n");
    out.push_str("        return Ok(format_auth_value(&stored.token));\n");
    out.push_str("    }\n");
    out.push_str("    bail!(\"missing authentication; set one of {:?} or run `{} auth set-token <token>`\", AUTH_ENV_VARS, GENERATED_CLI_NAME)\n");
    out.push_str("}\n\n");

    out.push_str("fn format_auth_value(raw: &str) -> String {\n");
    out.push_str("    if AUTH_KIND == \"oauth2-client-credentials\" && !raw.to_ascii_lowercase().starts_with(\"bearer \") {\n");
    out.push_str("        format!(\"Bearer {}\", raw)\n");
    out.push_str("    } else {\n");
    out.push_str("        raw.to_string()\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out
}

fn render_operation_runner(operation: &OperationRecord) -> String {
    let mut out = String::new();
    let path_expr = render_path_expression(operation);
    let query_expr = render_value_object(&operation.query_fields);
    let body_expr = render_value_object(&operation.body_fields);
    let args_binding = if operation.path_fields.is_empty()
        && operation.query_fields.is_empty()
        && operation.body_fields.is_empty()
    {
        "_args"
    } else {
        "args"
    };
    writeln!(
        out,
        "fn run_{}(base_url: &str, {}: {}) -> Result<()> {{",
        fn_suffix(operation),
        args_binding,
        args_struct_name(operation)
    )
    .unwrap();
    writeln!(out, "    let path = {};", path_expr).unwrap();
    if operation.requires_auth {
        out.push_str("    let auth = Some(resolve_auth_header()?);\n");
    } else {
        out.push_str("    let auth: Option<String> = None;\n");
    }
    writeln!(out, "    let query = {};", query_expr).unwrap();
    writeln!(out, "    let body = {};", body_expr).unwrap();
    out.push_str("    println!(\"{}\", serde_json::to_string_pretty(&json!({\n");
    writeln!(out, "        \"operation_id\": \"{}\",", escape_string(&operation.operation_id)).unwrap();
    writeln!(out, "        \"method\": \"{}\",", escape_string(&operation.method)).unwrap();
    out.push_str("        \"base_url\": base_url,\n");
    out.push_str("        \"path\": path,\n");
    out.push_str("        \"query\": query,\n");
    out.push_str("        \"body\": body,\n");
    out.push_str("        \"auth\": auth,\n");
    out.push_str("    }))?);\n");
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");
    out
}

fn render_path_expression(operation: &OperationRecord) -> String {
    if operation.path_fields.is_empty() {
        return format!("\"{}\".to_string()", escape_string(&operation.path));
    }
    let template = operation
        .path_fields
        .iter()
        .fold(operation.path.clone(), |acc, field| acc.replace(&format!("{{{}}}", field.name), "{}"));
    let args = operation
        .path_fields
        .iter()
        .map(|field| format!("args.{}", field.rust_name))
        .collect::<Vec<_>>()
        .join(", ");
    format!("format!(\"{}\", {})", escape_string(&template), args)
}

fn render_value_object(fields: &[OperationField]) -> String {
    if fields.is_empty() {
        return "serde_json::Value::Null".to_string();
    }
    let pairs = fields
        .iter()
        .map(|field| format!("\"{}\": args.{}", escape_string(&field.name), field.rust_name))
        .collect::<Vec<_>>()
        .join(", ");
    format!("json!({{{}}})", pairs)
}

fn auth_env_vars(manifest: &GeneratedManifest, auth: &AuthModel) -> Vec<AuthEnvVar> {
    if !auth.env_vars.is_empty() {
        return auth.env_vars.clone();
    }
    let prefix = upper_snake(&manifest.name);
    match auth.kind.as_str() {
        "oauth2-client-credentials" => vec![
            AuthEnvVar {
                name: format!("{}_ACCESS_TOKEN", prefix),
                kind: "per_call".to_string(),
                required: false,
                sensitive: true,
                description: "Bearer access token".to_string(),
            },
            AuthEnvVar {
                name: format!("{}_CLIENT_ID", prefix),
                kind: "auth_flow_input".to_string(),
                required: false,
                sensitive: false,
                description: "OAuth client id".to_string(),
            },
            AuthEnvVar {
                name: format!("{}_CLIENT_SECRET", prefix),
                kind: "auth_flow_input".to_string(),
                required: false,
                sensitive: true,
                description: "OAuth client secret".to_string(),
            },
        ],
        _ => vec![AuthEnvVar {
            name: format!("{}_API_KEY", prefix),
            kind: "per_call".to_string(),
            required: true,
            sensitive: true,
            description: "API credential".to_string(),
        }],
    }
}

fn usable_auth_env_vars(env_vars: &[AuthEnvVar], auth: &AuthModel) -> Vec<AuthEnvVar> {
    let per_call = env_vars
        .iter()
        .filter(|env_var| env_var.kind.is_empty() || env_var.kind == "per_call")
        .cloned()
        .collect::<Vec<_>>();
    if !per_call.is_empty() {
        return per_call;
    }
    if auth.kind == "oauth2-client-credentials" {
        return env_vars
            .iter()
            .filter(|env_var| env_var.name.ends_with("ACCESS_TOKEN"))
            .cloned()
            .collect::<Vec<_>>();
    }
    env_vars.to_vec()
}

fn render_readme(manifest: &GeneratedManifest) -> String {
    let auth_lines = manifest.auth.as_ref().map(|auth| {
        let env_vars = auth_env_vars(manifest, auth)
            .into_iter()
            .map(|env_var| format!("  - `{}`", env_var.name))
            .collect::<Vec<_>>()
            .join("\n");
        format!(
            "- Auth: {} ({})\n- Suggested env vars:\n{}\n",
            auth.scheme_name, auth.kind, env_vars
        )
    }).unwrap_or_else(|| "- Auth: none detected\n".to_string());
    format!(
        "# {}\n\nGenerated by `printing-press-rs`.\n\n- Source target: `{}`\n- Spec source: `{}`\n- Base URL: `{}`\n- Operations: {}\n{}",
        manifest.generated_crate,
        manifest.source_target,
        manifest.spec_source,
        manifest.base_url,
        manifest.operation_count,
        auth_lines,
    )
}

fn args_struct_name(operation: &OperationRecord) -> String {
    format!("{}Args", enum_variant(&operation.command_name))
}

fn fn_suffix(operation: &OperationRecord) -> String {
    operation.command_name.replace('-', "_")
}

fn enum_variant(command_name: &str) -> String {
    command_name
        .split('-')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => format!("{}{}", first.to_ascii_uppercase(), chars.as_str()),
                None => String::new(),
            }
        })
        .collect::<String>()
}

fn escape_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
